Jake flexible networks
jakew42/SelfBoostingNetworksOLD pull request #5
Opened 2018-06-25 15:30 UTC by jakew42

2018-06-25 18:31 UTC, DrKwint requested changes
I hope I didn't come off as harsh in the comments, I kinda zoned out as I was writing. I apologize if I did. Please hmu with any questions, and we'll make sure to run `yapf` and `pylint` before the final submission.

2018-06-25 18:31 UTC, DrKwint commented on boosted_classifier.py
> +            self._stem = stem(name='stem')
Why are you calling the passing `stem` argument? What is it supposed to be? This fn isn't documented, so I'm not sure what `stem` is supposed to be.

It appears as though this is calling a function to get a TITO callable that will then be usedin `build`. If that's the case, then this code is incorrect, as the TITO objects should constructed before being passed to `NaiveBoostedClassifier.__init__`. This is mostly because `NaiveBoostedClassifier` doesn't know what args the TITO constructor should take (e.g., number of neurons/filters in a layer, the stride of a conv, etc.).

It looks like the same case below with blocks and classifiers.

2018-06-25 18:31 UTC, DrKwint commented on networks.py
> +class IdentityBlock(snt.AbstractModule):
Do we need to define this? Why don't we just pass around the TITO callable `tf.identity` rather than using this heavyweight class?

2018-06-25 18:31 UTC, DrKwint commented on networks.py
> +class ReduceFlattenClassifier(snt.AbstractModule):
This naming isn't intuitive. I'm not really sure what this class is supposed to do. Maybe some documentation would help?

2018-06-25 18:31 UTC, DrKwint commented on networks.py
> +    def __init__(self, class_num, name='residual_classifier'):
Where did this `name` default argument come from? Does it have a connection to this class?

2018-06-25 18:31 UTC, DrKwint commented on networks.py
> +            self._block = snt.Sequential([
Does `snt.Sequential([snt.Conv2D(channels, 3), tf.nn.elu] + [snt.Residual(snt.Conv2D(channels, 3)), tf.nn.elu]*10)` work?

2018-06-25 18:31 UTC, DrKwint commented on networks.py
> +class BigConvStem(snt.AbstractModule):
Does this class do something that `lambda channels: snt.Sequential([snt.Conv2D(channels, 3), tf.nn.elu] + [snt.Residual(snt.Conv2D(channels, 3)), tf.nn.elu]*10)` doesn't?

2018-06-25 18:31 UTC, DrKwint commented on train.py
>  # define the model
Nitpicking, but the patch above this should be under this comment (I think?)

2018-06-25 18:31 UTC, DrKwint commented on train.py
> +for i in range(args.blocks):
Why not make this a pair of list comprehensions rather than a `for` loop? It would reduce the code size from 5 lines to 2 without unreasonable complexity (imo).

2018-06-25 19:07 UTC, jakew42 commented on boosted_classifier.py
> +            self._stem = stem(name='stem')
We've used the term "stem" in the previous few meetings. "Stem" refers to  the first portion of the network that does not have an associated classifier. I agree that the code base could use more documentation, though.

The code is not incorrect -- I have verified it builds the intended networks. The idea is to pass preconfigured pieces of the network. NaiveBoostedClassifier does not need to know details of how many neurons/filters/etc. I'm open to alternative architectures, but I don't believe that NaiveBoostedClassifier should be where we specify number of layers/filters/neurons for each block, as that would get rather unwieldy.

2018-06-25 19:08 UTC, jakew42 commented on networks.py
> +class IdentityBlock(snt.AbstractModule):
This fits in with the format of the other blocks and allows for the flexibility I wanted in NaiveBoostedClassifier.

If we end up changing that architecture, then perhaps we can do something less heavyweight here.

2018-06-25 19:10 UTC, jakew42 commented on networks.py
> +class ReduceFlattenClassifier(snt.AbstractModule):
Yup, definitely need more documentation here. This block exists to reduce the dimensionality from the ResNet blocks, flatten the data to work with dense layers, and then classify.

2018-06-25 19:12 UTC, jakew42 commented on networks.py
> +    def __init__(self, class_num, name='residual_classifier'):
I thought I'd fixed that. The name should match the class name. Thanks.

2018-06-25 19:12 UTC, jakew42 commented on networks.py
> +            self._block = snt.Sequential([
Yeah, that'd definitely be a better way. I'll implement this before merging.

2018-06-25 19:13 UTC, jakew42 commented on networks.py
> +class BigConvStem(snt.AbstractModule):
It fits into the block scheme I went with and allows for specification from the commandline. I do agree that it should be compacted, though.

2018-06-25 19:15 UTC, jakew42 commented on train.py
> +for i in range(args.blocks):
Yeah, that's reasonable.

2018-06-25 19:15 UTC, jakew42 commented on train.py
>  # define the model
Yup.

2018-06-26 19:20 UTC, DrKwint commented on boosted_classifier.py
> +            self._stem = stem(name='stem')
What is the type of `stem` as you're using it here?

2018-06-26 19:21 UTC, DrKwint commented on networks.py
> +class IdentityBlock(snt.AbstractModule):
How does this provide flexibility?

2018-06-26 19:26 UTC, DrKwint commented on networks.py
> +class BigConvStem(snt.AbstractModule):
You could make the lambda (or a named function) the value of the dict you're using to translate from command line args.

2018-06-27 17:32 UTC, DrKwint commented on networks.py
> +class IdentityBlock(snt.AbstractModule):
```
def IdentityBlock():
    return tf.identity
```

2018-06-27 17:35 UTC, DrKwint commented
Overall it sounds like we're pending Jake thinking about whether NaiveBoostedClassifier should take `Module` or `callable` objects (and a few small fixes here and there). This has a pile of implications for the codebase, so we'll get back to it once he's thought about it.

2018-06-28 17:25 UTC, DrKwint approved these changes

2018-06-28 17:26 UTC, merged